### ISSUE TITLE
HTTP Status 500 when accessing .bob files

### ISSUE THREAD

**Issue by zhuzzzzzz** [ornl-epics/dbwr#28]
![image](https://user-images.githubusercontent.com/57058943/236421845-0d161558-cbc3-4834-9e87-df7a71d151e1.png)

Under JRE17 and tomcat 9, I can successfully access localhost:8080/dbwr, but when I try to access my own .bob files using url like 'http://localhost:8080/dbwr/view.jsp?display=file:../../xxx.bob', it suggests 'Internal Server Error' and 'Could not initialize class dbwr.parser.WidgetFactory' in detail.

**Comment by kasemir** [comment]
There are two restrictions to file://.. URLs, see https://github.com/ornl-epics/dbwr#client-urls

1) The file://... URLs are resolved by tomcat, so they have to be in the file system of the server, not on some client computer that's running the web browser
2) To prevent access to file://etc/passwd and the like, the file:/.. path must be permitted by using the WHITELIST settings

**Comment by kasemir** [comment]
For first tests, use the example displays which are available via http:... from github:

`http://localhost:8080/dbwr/view.jsp?display=https://raw.githubusercontent.com/ControlSystemStudio/phoebus/master/app/display/model/src/main/resources/examples/01_main.bob`

**Comment by zhuzzzzzz** [comment]
> For first tests, use the example displays which are available via http:... from github:

this gets the same result as the picture above

**Comment by kasemir** [comment]
OK, so the error seems unrelated to the specific display file.
In fact, `Could not initialize class dbwr....` suggests that tomcat failed to load the application at all. You may be able to see the `view.jsp` web page, the basic HTML, but none of the application code works.

When you start tomcat, and/or when you redeploy the `dbwr.war` file, you should see something like this in the tomcat log:
```
17-Apr-2023 13:16:36.719 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/.../apache-tomcat-9.0.73/webapps/dbwr.war]
...
17-Apr-2023 13:16:36.815 INFO [main] dbwr.WebDisplayRepresentation.<clinit> No WHITELIST1 etc., allowing all display links
17-Apr-2023 13:16:36.815 INFO [main] dbwr.WebDisplayRepresentation.contextInitialized ===========================================
17-Apr-2023 13:16:36.815 INFO [main] dbwr.WebDisplayRepresentation.contextInitialized /dbwr started
17-Apr-2023 13:16:36.815 INFO [main] dbwr.WebDisplayRepresentation.contextInitialized ===========================================
17-Apr-2023 13:16:36.816 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [.../apache-tomcat-9.0.73/webapps/dbwr.war] has finished in [97] ms
```

Instead of such startup messages, I assume you get more `Could not initialize class..` errors as the dbwr.war fails to load.

Those messages suggest a basic incompatibility of the dbwr.war binary with the tomcat and/or jdk that you're using.
Could be trying to use tomcat 10+ instead of Tomcat 9, see #12.
Or using a binary that was compiled with a JDK that's newer than what you're using locally.

To avoid such issues, use Tomcat 9 (which I think you already do) and compile from sources, using the same JDK that you're using to run Tomcat.

**Comment by zhuzzzzzz** [comment]
Thanks, it's another problem of running env version. I switched to jdk19 and still use tomcat9, then re-deployed the project and it works.
